CODE_EXTENSIONS = [
    ".py", ".js", ".jsx", ".ts", ".tsx",
    ".java", ".c", ".h", ".cpp", ".cc", ".cxx",
    ".hpp", ".hh", ".hxx", ".cs", ".go", ".rs",
    ".rb", ".php", ".kt", ".kts", ".swift",
    ".scala", ".dart", ".lua", ".pl", ".pm",
    ".r", ".jl", ".zig", ".nim", ".ex", ".exs",
    ".erl", ".hrl", ".fs", ".fsi", ".fsx",
    ".ml", ".mli", ".hs", ".adb", ".ads",
    ".pas", ".f", ".f90", ".f95", ".f03", ".f08",
    ".cob", ".cbl", ".v", ".sv", ".svh",
    ".vhd", ".vhdl", ".m", ".mm", ".sql",
    ".proto", ".gql", ".graphql", ".clj",
    ".cljs", ".cljc", ".lisp", ".cl",
    ".el", ".vim", ".ps1", ".sh",
    ".fish", ".tcl", ".ahk", ".gd"
]

EXTENSION_TO_LANGUAGE = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".java": "java",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".hh": "cpp",
    ".hxx": "cpp",
    ".cs": "csharp",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".swift": "swift",
    ".scala": "scala",
    ".dart": "dart",
    ".lua": "lua",
    ".pl": "perl",
    ".pm": "perl",
    ".r": "r",
    ".jl": "julia",
    ".zig": "zig",
    ".nim": "nim",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hrl": "erlang",
    ".fs": "fsharp",
    ".fsi": "fsharp",
    ".fsx": "fsharp",
    ".ml": "ocaml",
    ".mli": "ocaml",
    ".hs": "haskell",
    ".adb": "ada",
    ".ads": "ada",
    ".pas": "pascal",
    ".f": "fortran",
    ".f90": "fortran",
    ".f95": "fortran",
    ".f03": "fortran",
    ".f08": "fortran",
    ".cob": "cobol",
    ".cbl": "cobol",
    ".v": "verilog",
    ".sv": "systemverilog",
    ".svh": "systemverilog",
    ".vhd": "vhdl",
    ".vhdl": "vhdl",
    ".m": "objc",
    ".mm": "objc",
    ".sql": "sql",
    ".proto": "proto",
    ".gql": "graphql",
    ".graphql": "graphql",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".cljc": "clojure",
    ".lisp": "commonlisp",
    ".cl": "commonlisp",
    ".el": "elisp",
    ".vim": "vim",
    ".ps1": "powershell",
    ".sh": "bash",
    ".fish": "fish",
    ".tcl": "tcl",
    ".ahk": "autohotkey",
    ".gd": "gdscript",
}

SUPPORTED_LANGUAGES = set(EXTENSION_TO_LANGUAGE.values())
